### ISSUE TITLE
Harmonize sees the Hue Hub but cannot sync + NameError: name 'baseurl' is not defined

### ISSUE THREAD

**Issue by Bboy486** [MCPCapital/harmonizeproject#15]
This is two issues in one. One is fixed. 

#1
The project sees the hue hub and when I press the button (or hold it down) I get an error that it has timed out have a nice day (something like that). I had to 
 cd harmonizeproject
and install from the folder. 

#2 After I did that I was able to add my hub. But I did receive the error below. 
Success! I generated a username and client key to access the bridge's Entertainment API!
Traceback (most recent call last):
  File "./harmonize.py", line 143, in <module>
    r = requests.get(url = baseurl+"/config")
NameError: name 'baseurl' is not defined

**Comment by evangryz** [comment]
Get the same #2 error

**Comment by SeattleSi** [comment]
I'm seeing issue #2 as well.

Traceback (most recent call last):
  File "./harmonizeproject/harmonize.py", line 143, in <module>
    r = requests.get(url = baseurl+"/config")
NameError: name 'baseurl' is not defined

However, after restarting ./harmonizeproject/harmonize.py I'm seeing:

Press return to stopException in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./harmonizeproject/harmonize.py", line 226, in averageimage
    coords[0] = ((coords[0])+1) * w//2 #Translates x value and resizes to video aspect ratio
NameError: name 'w' is not defined

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./harmonizeproject/harmonize.py", line 309, in buffer_to_light
    for i in rgb_bytes:
NameError: name 'rgb_bytes' is not defined

**Comment by MCPCapital** [comment]
For your # 1, I think this is the expected behavior. You gotta install the dependencies it before you can run it! I think it also generates client.json where your terminal session 'is'; but then always looks for it in the root directory. We can update the instructions to clarify you must cd into the directory first, thanks!

For your # 2, I can see this bug in the code now. The issue is we only define 'baseurl' IF client.json is found. If you haven't set it up yet, there is no client.json and thus you see the error you saw. I think it should run on the second try though, as  @SeattleSi pointed out. I'll label this a bug and get to fixing it as well.

Regarding @SeattleSi 's issue, first off, try again. Sometimes one thread gets ahead of another and doesn't define the video shape in time. If that doesn't work, you may have an issue getting video input. Does the videotest.py script work for you?

**Comment by MCPCapital** [comment]
I have some updates on this.

# 1 has been clarified in the Readme, telling users they must CD into the directory to generate the clientdata properly.

To clarify the issue with # 2 in this issue - it is that the below code which defines the baseurl is only triggered if Path("./client.json").is_file(): {See line 122}.  To fix this we need to include the below code in the 'else' tied to the same IF statement
```
    global baseurl
    baseurl = "http://{}/api".format(hueip)
```

For now I've included the workaround instructions in the Readme, but I will fix this in the code sometime soon. Thanks again for calling these out!

**Comment by Bboy486** [comment]
Thanks. When I re-ran the script I get the following

Multiple entertainment groups found ( {'3': {'name': 'Entertainment area LR', 'lights': ['1', '3', '19', '20', '21'], 'sensors': [], 'type': 'Entertainment', 'state': {'all_on': False, 'any_on': False}, 'recycle': False, 'class': 'TV', 'stream': {'proxymode': 'manual', 'proxynode': '/bridge', 'active': False, 'owner': None}, 'locations': {'1': [0.28, 0.74, 1.0], '3': [-0.29, 0.74, 0.0], '19': [0.02, 1.0, -1.0], '20': [0.76, 0.75, -1.0], '21': [-0.74, 0.75, 0.0]}, 'action': {'on': False, 'bri': 39, 'hue': 9159, 'sat': 63, 'effect': 'none', 'xy': [0.4113, 0.3946], 'ct': 292, 'alert': 'none', 'colormode': 'hs'}}, '4': {'name': 'Entertainment area Den', 'lights': ['5', '16', '6', '17'], 'sensors': [], 'type': 'Entertainment', 'state': {'all_on': False, 'any_on': False}, 'recycle': False, 'class': 'TV', 'stream': {'proxymode': 'auto', 'proxynode': '/lights/16', 'active': False, 'owner': None}, 'locations': {'5': [0.58, 0.84, 0.0], '16': [0.33, 0.85, 0.0], '6': [-0.55, 0.86, 0.0], '17': [-0.36, 0.87, 0.0]}, 'action': {'on': False, 'bri': 69, 'hue': 41436, 'sat': 77, 'effect': 'none', 'xy': [0.3129, 0.3291], 'ct': 153, 'alert': 'select', 'colormode': 'xy'}}} ) specify which with --groupid
3 = Entertainment area LR
4 = Entertainment area Den
You selected groupid
Traceback (most recent call last):
  File "./harmonize.py", line 187, in <module>
    light_locations = jsondata['locations']
KeyError: 'locations'
