### ISSUE TITLE
video capture troubleshooting

### ISSUE THREAD

**Issue by quexionjb** [MCPCapital/HarmonizeProject#45]
Hi -- trying this out with a raspberrypi5. Getting some errors. video0 shows up as a device. I could use some help troubleshooting harmonize.py and videotest.py:

```
(harmonize_env) pi@raspberrypi5:~/HarmonizeProject $ ./harmonize.py -l 0 -a 8
--- Starting Harmonize Project ---
INFO: Single Hue bridge detected on network via mDNS.
Querying hue bridge for entertainment areas on local network.
groupid =  200
Using Entertainment area with group_id: 200
Starting computer vision engine...
INFO: Detected video capture card on /dev/video0
[ WARN:0@1.754] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@1.754] global cap.cpp:342 open VIDEOIO(GSTREAMER): backend is generally available but can't be used to capture by index
Disabling streaming on Entertainment area...
ERROR: Unable to open capture device.
```

and for the videotest:

```
(harmonize_env) pi@raspberrypi5:~/HarmonizeProject $ python3 videotest.py
Press ESC to exit.
Traceback (most recent call last):
  File "/home/pi/HarmonizeProject/videotest.py", line 12, in <module>
    cv2.namedWindow("preview")
cv2.error: OpenCV(4.10.0) /home/pi/opencv/modules/highgui/src/window_gtk.cpp:638: error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'
```

**Comment by quexionjb** [comment]
Now I'm thinking it might be permissions plus a python path issue. Looks like this raspberry pi has python 3.11. I get this error when I sudo the videotest:

```
(harmonize_env) pi@raspberrypi5:~/HarmonizeProject $ sudo python3 jb.py
Traceback (most recent call last):
  File "/home/pi/HarmonizeProject/videotest.py", line 3, in <module>
    import cv2             # Script Last Updated - Release 1.1.2
    ^^^^^^^^^^
ModuleNotFoundError: No module named 'cv2'
```

**Comment by quexionjb** [comment]
ok, yeah. I'm going to hose my raspberrypi and start completely from scratch with a new OS. I'll close this issue for now. Stay tuned...

**Comment by quexionjb** [comment]
close for now
