### ISSUE TITLE
PI OS

### ISSUE THREAD

**Issue by el-ch13fo** [MCPCapital/harmonizeproject#7]
Hello, I am trying to install this on my PI4 using Rasbian Buster Lite OS but it seems to encounter a lot of missing dependencies. What OS should I be using? I already purchased a HDMI - USB capture card but have been having difficulties getting this thing to run. Any help would be appreciated. Thanks

**Comment by THATDONFC** [comment]
I'm also seeing a bunch of errors. Currently, I'm hung up on this one:

```
running install
running bdist_egg
running egg_info
writing src/python_mbedtls.egg-info/PKG-INFO
writing dependency_links to src/python_mbedtls.egg-info/dependency_links.txt
writing requirements to src/python_mbedtls.egg-info/requires.txt
writing top-level names to src/python_mbedtls.egg-info/top_level.txt
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_platform.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/tls.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/hkdf.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/version.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/x509.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/exceptions.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_random.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_ringbuf.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_md.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/mpi.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/pk.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/cipher/_cipher.c' Cython extension (up-to-date)
reading manifest file 'src/python_mbedtls.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/python_mbedtls.egg-info/SOURCES.txt'
installing library code to build/3.7.3/bdist.linux-armv7l/egg
running install_lib
running build_py
running build_ext
building 'mbedtls._platform' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_platform.c -o build/3.7.3/temp.linux-armv7l-3.7/build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_platform.o
build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_platform.c:788:10: fatal error: mbedtls/platform_util.h: No such file or directory
 #include "mbedtls/platform_util.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by afm2** [comment]
I'm getting this error as well running Raspian Buster on a Pi4.

**Comment by evangryz** [comment]
Seems to be a common error, as I am getting this on my Pi4 as well!

**Comment by stevoleeto** [comment]
is mbed_tls an actual dependency of this?

**Comment by surrealillusion** [comment]
Is anyone seeing a dependency error between libjpeg62-turbo and a conflict with libjpeg62? Testing out the build on buster-lite on a Pi 3B

**Comment by smurkcs** [comment]
i'm also seeing the errors reported in this thread.. mbedtls/bignum.h missing file and libjpeg62-turbo conflict.. Pi 4B - any word on this atm?

**Comment by OpticalTomcat** [comment]
I had the same issues. I ran these steps to address the opencv issue: https://pimylifeup.com/raspberry-pi-opencv/
I commented the mbed_tls import out and it seemed to work fine.

**Comment by surrealillusion** [comment]
> Is anyone seeing a dependency error between libjpeg62-turbo and a conflict with libjpeg62? Testing out the build on buster-lite on a Pi 3B

To address my issue, I modified the setup.sh to use libpeg62-turbo instead and all of the dependancies were met. I was able to execute the Python script afterwards and everything appears to be working. Just need to see if there's an option to intensify the light a bit as I found some scenes to be relatively dim while watching some videos.

**Comment by MCPCapital** [comment]
Hello all. I apologize for being late to address this, work has kept me very busy recently. I will try to address all of the issues here and ask for some clarifications. I will say though, getting OpenCV and Mbedtls installed has always been a pain for me.

@smurkcs @surrealillusion - Regarding libjpeg62 and libjpeg62-turbo, we have removed libjpeg62 from the dependencies and that issue should now be resolved.

@AdrianTM helped with the OpenCV dependencies and some other python dependencies, which should be able to be installed via APT now. I've also included the guide @OpticalTomcat linked in case users have an issue with the APT installation. Thanks for that!

@THATDONFC 's error is related to the compilation of MbedTLS. Not sure how to address this at the moment, or if it needs to be addressed in light of @OpticalTomcat 's observation that this works without mbedtls. It was my understanding that using the PSK-AES128-GCM-SHA256 cipher to send data to the bridge required mbedtls.

I am hoping the updates I just made resolve the OpenCV dependencies. I'd like to gain some greater insight into if mbedtls is actually required before I remove it as a dependency entirely - Can anyone else confirm that the script will run without mbedtls?

**Comment by smurkcs** [comment]
works well, but lights are still pretty dim. also getting `VIDEOIO ERROR: V4L2: setting property #38 is not supported` every time the script starts

**Comment by MCPCapital** [comment]
@smurkcs I'm glad to hear it is working for you. Did you install mbedtls? I want to verify mbedtls is not needed so I can remove it from the dependencies.

Regarding `VIDEOIO ERROR: V4L2: setting property #38 is not supported` - This is related to setting the buffer size for the incoming video. We set it to 0 so we always get the latest frame. I haven't encountered this error on the two video capture cards I've tried though so I think it may be your capture card. Is there significant delay between the video and lights for you? You could try setting the buffer size to 1 in the script, though I'm not sure that would work either as I'm not too familiar with that error.

**Comment by el-ch13fo** [comment]
I just re-tried and it installed properly, thanks for that. But now, my issue is with executing the harmonize.py script.

`pi@raspberrypi:~/harmonizeproject $ sudo ./harmonize.py
I will use the bridge at  192.168.0.200
Multiple entertainment groups found ( {'4': {'name': 'Living Room TV', 'lights': ['11', '9', '10', '12'], 'sensors': [], 'type': 'Entertainment', 'state': {'all_on': False, 'any_on': False}, 'recycle': False, 'class': 'TV', 'stream': {'proxymode': 'auto', 'proxynode': '/lights/12', 'active': False, 'owner': None}, 'locations': {'11': [-0.03, 1.0, 1.0], '9': [-0.42, 1.0, -1.0], '10': [0.38, 1.0, -1.0], '12': [-0.02, 0.77, -1.0]}, 'action': {'on': False, 'bri': 7, 'hue': 41826, 'sat': 77, 'effect': 'none', 'xy': [0.3128, 0.3255], 'ct': 153, 'alert': 'none', 'colormode': 'xy'}}, '6': {'name': 'Theater', 'lights': ['14', '13'], 'sensors': [], 'type': 'Entertainment', 'state': {'all_on': False, 'any_on': False}, 'recycle': False, 'class': 'TV', 'stream': {'proxymode': 'auto', 'proxynode': '/lights/14', 'active': False, 'owner': None}, 'locations': {'14': [0.68, 0.68, -1.0], '13': [-0.71, 0.68, -1.0]}, 'action': {'on': False, 'bri': 254, 'hue': 8418, 'sat': 140, 'effect': 'none', 'xy': [0.4573, 0.41], 'ct': 366, 'alert': 'select', 'colormode': 'ct'}}} ) specify which with --groupid
4 = Living Room TV
6 = Theater
6
You selected groupid  6
Press return to stop[ WARN:0] global /home/pi/opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global /home/pi/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./harmonize.py", line 226, in averageimage
    coords[0] = ((coords[0])+1) * w//2 #Translates x value and resizes to video aspect ratio
NameError: name 'w' is not defined

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./harmonize.py", line 309, in buffer_to_light
    for i in rgb_bytes:
NameError: name 'rgb_bytes' is not defined`

**Comment by smurkcs** [comment]
> @smurkcs I'm glad to hear it is working for you. Did you install mbedtls? I want to verify mbedtls is not needed so I can remove it from the dependencies.

Thanks for the response! I did a fresh install and included the separate mbedtls install from the readme. MBEDTLS DONE , FULLY COMPLETE messages. All is working exactly as well as before, but with fewer 'corrupted jpeg' errors as its running. lights still dim, but very much at great sync latency. 

Will see if I can play with some hardware settings to get that brightness up, thanks again for this killer app!

**Comment by evangryz** [comment]
My install also is now working, but I am receiving the following error:
Success! I generated a username and client key to access the bridge’s Entertainment API!
Traceback (most recent call last):
      File “./harmonize.py”, line 143, in <module>
           r = requests.get(url = baseurl+”/config”)
NameError: name ‘baseurl’ is not defined 

If anyone found a way to fix this please let me know!

**Comment by el-ch13fo** [comment]
Now it can't find the Hue bridge...
pi@raspberrypi:~/harmonizeproject $ ./harmonize.py
I will use the bridge at  192.168.0.200
Hue bridge not found. Mission failed, better luck next time
pi@raspberrypi:~/harmonizeproject $

**Comment by MCPCapital** [comment]
Thanks for the replies everyone!

@el-ch13fo I haven't seen this error before, but it seems that its related to gstreamer not being installed properly or something similar. If it works for you, which it sounds like it does, I think its OK. Some people get some odd warnings when using various capture cards.

@smurkcs Glad you are enjoying 👍 

@evangryz This is a bug that was just discovered in #15 ! So the workaround is to be sure that you 'cd' into the harmonizeproject directory before running it the first time. Then, run it and pair your bridge, and it'll exit with an error, but it will have saved the bridge API information. After that, it should run smoothly. Report back if its not working!

Thanks again all!

**Comment by MCPCapital** [comment]
I have confirmed that mbedtls is not needed and have removed it from the dependencies across the repository.

For the cv2 property setting issue, I will place line 288 {cap.set(cv2.CAP_PROP_BUFFERSIZE,0)} in a 'try' as it may increase performance on some cards but is not essential. Then I will close the issue.

If anyone has any additional input please let me know.
